# Generated by Django 6.0.7 on 2026-08-04 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('paypal', 'PayPal')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Confirmation'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('external_reference', models.CharField(blank=True, help_text='Transaction ID returned by the provider', max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['external_reference'], name='payments_pa_externa_e30da4_idx')],
            },
        ),
    ]
