# Generated by Django 6.0.7 on 2026-08-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('flutterwave', 'Card / Bank Transfer (Flutterwave)'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
