# Generated by Django 6.0.7 on 2026-08-04 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('rw', 'Kinyarwanda'), ('sw', 'Swahili')], default='en', max_length=5)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.authorprofile')),
            ],
            options={
                'db_table': 'catalog_book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('epub', 'EPUB'), ('pdf', 'PDF')], max_length=5)),
                ('encrypted_file', models.FileField(upload_to='book_assets/')),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(help_text='Checksum of the plaintext original', max_length=64)),
                ('wrapped_key', models.TextField(help_text="Book's DEK, encrypted with the master key")),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('virus_scan_passed', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='catalog.book')),
            ],
            options={
                'db_table': 'catalog_book_asset',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'catalog_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='catalog_boo_status_b30b19_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='catalog_boo_languag_2b6c7f_idx'),
        ),
    ]
